### ISSUE TITLE
Image converter crashes with error

### ISSUE THREAD

**Issue by sandeepdutta** [NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline#44]
Hello,

I am trying to run image converter it crashes with the following error. I have also attached the launch file.
Any help would be greatly appreciated.
All packages from this package crashes with similar messages. Iam using the isaac_ros docker container
as recommended by you. Other packages like isaac_ros_visual_slam & isaac_ros_appriltag are working
fine onb tje same docker image.

Thank you
Sandeep
ros2 launch isaac_ros_image_proc isaac_ros_image_converter.launch.py 
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2024-02-26-08-32-07-426879-orin-agx-12645
[INFO] [launch]: Default logging verbosity is set to INFO
[WARNING] [launch_ros.actions.node]: Parameter file path is not a file: encoding_desiredRGB_U8
[INFO] [component_container_mt-1]: process started with pid [12656]
[component_container_mt-1] [INFO] [1708965127.984097399] [argus_mono_container]: Load Library: /workspaces/isaac_ros_stuff/install/isaac_ros_image_proc/lib/libimage_format_converter_node.so
[component_container_mt-1] [INFO] [1708965128.043858086] [argus_mono_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::image_proc::ImageFormatConverterNode>
[component_container_mt-1] [INFO] [1708965128.044006683] [argus_mono_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::image_proc::ImageFormatConverterNode>
[component_container_mt-1] [INFO] [1708965128.052249641] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container_mt-1] [INFO] [1708965128.052519535] [image_format_converter_node]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [INFO] [1708965128.054579763] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container_mt-1] [INFO] [1708965128.063543782] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container_mt-1] [INFO] [1708965128.068409431] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container_mt-1] [INFO] [1708965128.073559663] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container_mt-1] [INFO] [1708965128.078310863] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros_stuff/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container_mt-1] [INFO] [1708965128.079467218] [NitrosContext]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1708965128.083126744] [NitrosContext]: [NitrosContext] Running application...
[component_container_mt-1] 2024-02-26 08:32:08.083 WARN  gxf/std/program.cpp@514: No system specified. Nothing to do
[component_container_mt-1] [INFO] [1708965128.085283689] [image_format_converter_node]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1708965128.085356211] [image_format_converter_node]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1708965128.088075380] [image_format_converter_node]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1708965128.088209223] [image_format_converter_node]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1708965128.093635206] [image_format_converter_node]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1708965128.093765177] [image_format_converter_node]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1708965128.094268640] [image_format_converter_node]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1708965128.095183073] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container_mt-1] [INFO] [1708965128.097705606] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container_mt-1] [INFO] [1708965128.099333356] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/image_proc/libgxf_tensorops.so
[component_container_mt-1] [INFO] [1708965128.108414576] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/multimedia/libgxf_multimedia.so
[component_container_mt-1] [INFO] [1708965128.109363735] [image_format_converter_node]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1708965128.111578000] [image_format_converter_node]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1708965128.192143186] [image_format_converter_node]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [INFO] [1708965128.211132016] [image_format_converter_node]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1708965128.218819631] [image_format_converter_node]: [NitrosNode] Starting negotiation...
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/image_format_converter_node' in container '/argus_mono_container'
[component_container_mt-1] [INFO] [1708965129.219676043] [image_format_converter_node]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1708965129.219841410] [image_format_converter_node]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1708965129.219881512] [image_format_converter_node]: [NitrosPublisher] Negotiation ended with no results
[component_container_mt-1] [INFO] [1708965129.219904939] [image_format_converter_node]: [NitrosPublisher] Use only the compatible publisher: topic_name="/image", data_format="nitros_image_bgr8"
[component_container_mt-1] [INFO] [1708965129.219927310] [image_format_converter_node]: [NitrosSubscriber] Negotiation ended with no results
[component_container_mt-1] [INFO] [1708965129.219943696] [image_format_converter_node]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/image_raw", data_format="nitros_image_mono8"
[component_container_mt-1] [INFO] [1708965129.220532867] [image_format_converter_node]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1708965129.237941656] [image_format_converter_node]: [NitrosNode] Wrote the final top level YAML graph to "/tmp/isaac_ros_nitros/graphs/PUJCFOPRDR/PUJCFOPRDR.yaml"
[component_container_mt-1] [INFO] [1708965129.238074091] [image_format_converter_node]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1708965129.238088557] [image_format_converter_node]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1708965129.238106640] [image_format_converter_node]: [NitrosContext] Loading application: '/tmp/isaac_ros_nitros/graphs/PUJCFOPRDR/PUJCFOPRDR.yaml'
[component_container_mt-1] [INFO] [1708965129.239826114] [image_format_converter_node]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [INFO] [1708965129.240101705] [image_format_converter_node]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1708965129.240130797] [image_format_converter_node]: [ImageFormatConverterNode] postLoadGraphCallback().
[component_container_mt-1] [INFO] [1708965129.240145871] [image_format_converter_node]: [NitrosContext] Initializing application...
[component_container_mt-1] 2024-02-26 08:32:09.609 ERROR /workspaces/isaac_ros_stuff/src/isaac_ros_image_pipeline/isaac_ros_image_proc/gxf/tensorops/extensions/tensorops/components/TensorStream.cpp@104: tensor stream creation failed.
[component_container_mt-1] 2024-02-26 08:32:09.609 ERROR gxf/std/entity_warden.cpp@406: Failed to initialize component 00030 (stream)
[component_container_mt-1] 2024-02-26 08:32:09.609 ERROR gxf/core/runtime.cpp@685: Could not initialize entity 'PUJCFOPRDR_resource' (E28): GXF_FAILURE
[component_container_mt-1] 2024-02-26 08:32:09.609 ERROR gxf/std/program.cpp@236: Failed to activate entity 00028 named PUJCFOPRDR_resource: GXF_FAILURE
[component_container_mt-1] 2024-02-26 08:32:09.609 ERROR gxf/std/program.cpp@238: Deactivating...
[component_container_mt-1] 2024-02-26 08:32:09.626 ERROR gxf/core/runtime.cpp@1384: Graph activation failed with error: GXF_FAILURE
[component_container_mt-1] [ERROR] [1708965129.626251792] [image_format_converter_node]: [NitrosContext] GxfGraphActivate Error: GXF_FAILURE
[component_container_mt-1] [ERROR] [1708965129.626417031] [image_format_converter_node]: [NitrosNode] runGraphAsync Error: GXF_FAILURE
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] runGraphAsync Error: GXF_FAILURE
[ERROR] [component_container_mt-1]: process has died [pid 12656, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args --log-level info --ros-args -r __node:=argus_mono_container -r __ns:=/ -r image_raw:=/camera/rs_top/infra1/image_rect_raw -r camera_info:=/camera/rs_top/infra1/camera_info'].
[isaac_ros_image_converter.launch.py.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline/files/14407654/isaac_ros_image_converter.launch.py.txt)

**Comment by jaiveersinghNV** [comment]
It looks like you specified your parameters in the wrong spot in your launch file. The `encoding_desired` is a parameter of the Image Format Converter `ComposableNode`, *not* of the `ComposableNodeContainer`. If you move the parameter up to around line 26, that should fix the problem.

**Comment by sandeepdutta** [comment]
Hello Jaiveer,

Thank you for the prompt response. I have made the change you suggested .. I still get the same error. I have set the log-level to "debug" to give you more information. I have also attached the latest launch file.

Thank you.
Sandeep
[isaac_ros_image_converter.launch.py.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline/files/14440410/isaac_ros_image_converter.launch.py.txt)
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2024-02-28-14-09-53-846123-orin-agx-288853
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container_mt-1]: process started with pid [288864]
[component_container_mt-1] [DEBUG] [1709158194.158077033] [rclcpp]: signal handler installed
[component_container_mt-1] [DEBUG] [1709158194.158112905] [rclcpp]: deferred_signal_handler(): waiting for SIGINT/SIGTERM or uninstall
[component_container_mt-1] [DEBUG] [1709158194.158291659] [rcl]: Initializing wait set with '0' subscriptions, '2' guard conditions, '0' timers, '0' clients, '0' services
[component_container_mt-1] [DEBUG] [1709158194.158391756] [rcl]: Initializing node 'ComponentManager' in namespace ''
[component_container_mt-1] [DEBUG] [1709158194.158421293] [rcl]: Using domain ID of '0'
[component_container_mt-1] [DEBUG] [1709158194.168442200] [rcl]: Initializing publisher for topic name '/rosout'
[component_container_mt-1] [DEBUG] [1709158194.168527321] [rcl]: Expanded and remapped topic name '/rosout'
[component_container_mt-1] [DEBUG] [1709158194.170747985] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.170792914] [rcl]: Node initialized
[component_container_mt-1] [DEBUG] [1709158194.171151573] [rcl]: Initializing subscription for topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.171170294] [rcl]: Expanded and remapped topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.173398798] [rcl]: Subscription initialized
[component_container_mt-1] [DEBUG] [1709158194.173664496] [rcl]: Initializing service for service name '~/_container/load_node'
[component_container_mt-1] [DEBUG] [1709158194.173682737] [rcl]: Expanded and remapped service name '/argus_mono_container/_container/load_node'
[component_container_mt-1] [DEBUG] [1709158194.174656795] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.174680475] [rmw_fastrtps_cpp]: Sub Topic rq/argus_mono_container/_container/load_nodeRequest
[component_container_mt-1] [DEBUG] [1709158194.174686171] [rmw_fastrtps_cpp]: Pub Topic rr/argus_mono_container/_container/load_nodeReply
[component_container_mt-1] [DEBUG] [1709158194.174689659] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.174746556] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.174791357] [rcl]: Initializing service for service name '~/_container/unload_node'
[component_container_mt-1] [DEBUG] [1709158194.174803485] [rcl]: Expanded and remapped service name '/argus_mono_container/_container/unload_node'
[component_container_mt-1] [DEBUG] [1709158194.175219617] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.175234561] [rmw_fastrtps_cpp]: Sub Topic rq/argus_mono_container/_container/unload_nodeRequest
[component_container_mt-1] [DEBUG] [1709158194.175240289] [rmw_fastrtps_cpp]: Pub Topic rr/argus_mono_container/_container/unload_nodeReply
[component_container_mt-1] [DEBUG] [1709158194.175244481] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.175281410] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.175310658] [rcl]: Initializing service for service name '~/_container/list_nodes'
[component_container_mt-1] [DEBUG] [1709158194.175320898] [rcl]: Expanded and remapped service name '/argus_mono_container/_container/list_nodes'
[component_container_mt-1] [DEBUG] [1709158194.175773863] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.175791559] [rmw_fastrtps_cpp]: Sub Topic rq/argus_mono_container/_container/list_nodesRequest
[component_container_mt-1] [DEBUG] [1709158194.175796839] [rmw_fastrtps_cpp]: Pub Topic rr/argus_mono_container/_container/list_nodesReply
[component_container_mt-1] [DEBUG] [1709158194.175800743] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.175834856] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.175904776] [rcl]: Initializing wait set with '0' subscriptions, '2' guard conditions, '0' timers, '0' clients, '0' services
[component_container_mt-1] [DEBUG] [1709158194.379285456] [rcl]: Service server taking service request
[component_container_mt-1] [DEBUG] [1709158194.379481650] [rcl]: Service take request succeeded: true
[component_container_mt-1] [INFO] [1709158194.380446428] [argus_mono_container]: Load Library: /workspaces/isaac_ros_stuff/install/isaac_ros_image_proc/lib/libimage_format_converter_node.so
[component_container_mt-1] [INFO] [1709158194.429421834] [argus_mono_container]: Found class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::image_proc::ImageFormatConverterNode>
[component_container_mt-1] [INFO] [1709158194.429531147] [argus_mono_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nvidia::isaac_ros::image_proc::ImageFormatConverterNode>
[component_container_mt-1] [DEBUG] [1709158194.429642253] [rcl]: Arg 1 (-r) is not a --param nor a -p flag.
[component_container_mt-1] [DEBUG] [1709158194.429664589] [rcl]: Got remap rule : __node:=image_format_converter_node
[component_container_mt-1] 
[component_container_mt-1] [DEBUG] [1709158194.429689005] [rcl]: Initializing node 'NitrosNode' in namespace ''
[component_container_mt-1] [DEBUG] [1709158194.429709229] [rcl]: Using domain ID of '0'
[component_container_mt-1] [DEBUG] [1709158194.430155410] [rcl]: Initializing publisher for topic name '/rosout'
[component_container_mt-1] [DEBUG] [1709158194.430271283] [rcl]: Expanded and remapped topic name '/rosout'
[component_container_mt-1] [DEBUG] [1709158194.431100956] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.431123197] [rcl]: Node initialized
[component_container_mt-1] [DEBUG] [1709158194.431229470] [rcl]: Initializing service for service name 'image_format_converter_node/get_parameters'
[component_container_mt-1] [DEBUG] [1709158194.431242206] [rcl]: Expanded and remapped service name '/image_format_converter_node/get_parameters'
[component_container_mt-1] [DEBUG] [1709158194.431993798] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.432016774] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/get_parametersRequest
[component_container_mt-1] [DEBUG] [1709158194.432022214] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/get_parametersReply
[component_container_mt-1] [DEBUG] [1709158194.432025510] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.432277705] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.432327690] [rcl]: Initializing service for service name 'image_format_converter_node/get_parameter_types'
[component_container_mt-1] [DEBUG] [1709158194.432340682] [rcl]: Expanded and remapped service name '/image_format_converter_node/get_parameter_types'
[component_container_mt-1] [DEBUG] [1709158194.432975504] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.432994545] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/get_parameter_typesRequest
[component_container_mt-1] [DEBUG] [1709158194.432999857] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/get_parameter_typesReply
[component_container_mt-1] [DEBUG] [1709158194.433004657] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.433218387] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.433263412] [rcl]: Initializing service for service name 'image_format_converter_node/set_parameters'
[component_container_mt-1] [DEBUG] [1709158194.433275636] [rcl]: Expanded and remapped service name '/image_format_converter_node/set_parameters'
[component_container_mt-1] [DEBUG] [1709158194.433883738] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.433902266] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/set_parametersRequest
[component_container_mt-1] [DEBUG] [1709158194.433907834] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/set_parametersReply
[component_container_mt-1] [DEBUG] [1709158194.433911835] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.434127645] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.434171325] [rcl]: Initializing service for service name 'image_format_converter_node/set_parameters_atomically'
[component_container_mt-1] [DEBUG] [1709158194.434184445] [rcl]: Expanded and remapped service name '/image_format_converter_node/set_parameters_atomically'
[component_container_mt-1] [DEBUG] [1709158194.434764836] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.434780612] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/set_parameters_atomicallyRequest
[component_container_mt-1] [DEBUG] [1709158194.434785220] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/set_parameters_atomicallyReply
[component_container_mt-1] [DEBUG] [1709158194.434788580] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.434958470] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.434994406] [rcl]: Initializing service for service name 'image_format_converter_node/describe_parameters'
[component_container_mt-1] [DEBUG] [1709158194.435005670] [rcl]: Expanded and remapped service name '/image_format_converter_node/describe_parameters'
[component_container_mt-1] [DEBUG] [1709158194.435479499] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.435495308] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/describe_parametersRequest
[component_container_mt-1] [DEBUG] [1709158194.435500556] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/describe_parametersReply
[component_container_mt-1] [DEBUG] [1709158194.435504076] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.436017873] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.436059442] [rcl]: Initializing service for service name 'image_format_converter_node/list_parameters'
[component_container_mt-1] [DEBUG] [1709158194.436070546] [rcl]: Expanded and remapped service name '/image_format_converter_node/list_parameters'
[component_container_mt-1] [DEBUG] [1709158194.436859674] [rmw_fastrtps_cpp]: ************ Service Details *********
[component_container_mt-1] [DEBUG] [1709158194.436879610] [rmw_fastrtps_cpp]: Sub Topic rq/image_format_converter_node/list_parametersRequest
[component_container_mt-1] [DEBUG] [1709158194.436962587] [rmw_fastrtps_cpp]: Pub Topic rr/image_format_converter_node/list_parametersReply
[component_container_mt-1] [DEBUG] [1709158194.436969787] [rmw_fastrtps_cpp]: ***********
[component_container_mt-1] [DEBUG] [1709158194.437160125] [rcl]: Service initialized
[component_container_mt-1] [DEBUG] [1709158194.437207006] [rcl]: Initializing publisher for topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.437220606] [rcl]: Expanded and remapped topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.437961574] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.438236009] [rcl]: Initializing subscription for topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.438254409] [rcl]: Expanded and remapped topic name '/parameter_events'
[component_container_mt-1] [DEBUG] [1709158194.438929840] [rcl]: Subscription initialized
[component_container_mt-1] [INFO] [1709158194.439883675] [NitrosContext]: [NitrosContext] Creating a new shared context
[component_container_mt-1] [INFO] [1709158194.440095581] [image_format_converter_node]: [NitrosNode] Initializing NitrosNode
[component_container_mt-1] [DEBUG] [1709158194.440341376] [NitrosContext]: [NitrosContext] Creating a local context based on an existing shared context
[component_container_mt-1] [INFO] [1709158194.441739343] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/std/libgxf_std.so
[component_container_mt-1] [INFO] [1709158194.449162686] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_gxf_helpers.so
[component_container_mt-1] [INFO] [1709158194.453508109] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_sight.so
[component_container_mt-1] [INFO] [1709158194.458187519] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/libgxf_atlas.so
[component_container_mt-1] [INFO] [1709158194.462920946] [NitrosContext]: [NitrosContext] Loading application: '/workspaces/isaac_ros_stuff/install/isaac_ros_nitros/share/isaac_ros_nitros/config/type_adapter_nitros_context_graph.yaml'
[component_container_mt-1] [INFO] [1709158194.464174591] [NitrosContext]: [NitrosContext] Initializing application...
[component_container_mt-1] [INFO] [1709158194.468399917] [NitrosContext]: [NitrosContext] Running application...
[component_container_mt-1] 2024-02-28 14:09:54.468 WARN  gxf/std/program.cpp@514: No system specified. Nothing to do
[component_container_mt-1] [DEBUG] [1709158194.469045268] [image_format_converter_node]: [NitrosNode] Type negotiation duration (seconds) = 1
[component_container_mt-1] [DEBUG] [1709158194.469108724] [image_format_converter_node]: [NitrosNode] Namespace = XYWCBZJCLI
[component_container_mt-1] [DEBUG] [1709158194.469890909] [image_format_converter_node]: [NitrosNode] Package's directory: /workspaces/isaac_ros_stuff/install/isaac_ros_image_proc/share/isaac_ros_image_proc
[component_container_mt-1] [DEBUG] [1709158194.470440355] [image_format_converter_node]: [NitrosNode] Nitros's directory: /workspaces/isaac_ros_stuff/install/isaac_ros_nitros/share/isaac_ros_nitros
[component_container_mt-1] [DEBUG] [1709158194.470585924] [image_format_converter_node]: [ImageFormatConverterNode] Constructor
[component_container_mt-1] [INFO] [1709158194.470619013] [image_format_converter_node]: [ImageFormatConverterNode] Set output data format to: "nitros_image_rgb8"
[component_container_mt-1] [INFO] [1709158194.470751302] [image_format_converter_node]: [NitrosNode] Starting NitrosNode
[component_container_mt-1] [INFO] [1709158194.470766534] [image_format_converter_node]: [NitrosNode] Loading built-in preset extension specs
[component_container_mt-1] [INFO] [1709158194.473378402] [image_format_converter_node]: [NitrosNode] Loading built-in extension specs
[component_container_mt-1] [INFO] [1709158194.473423651] [image_format_converter_node]: [NitrosNode] Loading preset extension specs
[component_container_mt-1] [INFO] [1709158194.478662171] [image_format_converter_node]: [NitrosNode] Loading extension specs
[component_container_mt-1] [INFO] [1709158194.478729596] [image_format_converter_node]: [NitrosNode] Loading generator rules
[component_container_mt-1] [INFO] [1709158194.479157760] [image_format_converter_node]: [NitrosNode] Loading extensions
[component_container_mt-1] [INFO] [1709158194.479923401] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/libgxf_message_compositor.so
[component_container_mt-1] [INFO] [1709158194.482501380] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/cuda/libgxf_cuda.so
[component_container_mt-1] [INFO] [1709158194.484391832] [image_format_converter_node]: [NitrosContext] Loading extension: gxf/lib/image_proc/libgxf_tensorops.so
[component_container_mt-1] [INFO] [1709158194.492951924] [NitrosContext]: [NitrosContext] Loading extension: gxf/lib/multimedia/libgxf_multimedia.so
[component_container_mt-1] [INFO] [1709158194.493972895] [image_format_converter_node]: [NitrosNode] Loading graph to the optimizer
[component_container_mt-1] [INFO] [1709158194.496194743] [image_format_converter_node]: [NitrosNode] Running optimization
[component_container_mt-1] [INFO] [1709158194.568490143] [image_format_converter_node]: [NitrosNode] Obtaining graph IO group info from the optimizer
[component_container_mt-1] [DEBUG] [1709158194.581292041] [image_format_converter_node.NitrosNode]: Supported data format combinations:
[component_container_mt-1] [DEBUG] [1709158194.581355274] [image_format_converter_node.NitrosNode]: #1 I/O group:
[component_container_mt-1] [DEBUG] [1709158194.581362698] [image_format_converter_node.NitrosNode]: 	#1 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581370666] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581376874] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581382090] [image_format_converter_node.NitrosNode]: 	#2 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581386506] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581390954] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581394954] [image_format_converter_node.NitrosNode]: 	#3 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581399018] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581402986] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581406890] [image_format_converter_node.NitrosNode]: 	#4 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581410858] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581414858] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581419050] [image_format_converter_node.NitrosNode]: 	#5 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581423274] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581428074] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581432554] [image_format_converter_node.NitrosNode]: 	#6 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581436970] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581441706] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581446378] [image_format_converter_node.NitrosNode]: 	#7 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581450859] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581455339] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581459691] [image_format_converter_node.NitrosNode]: 	#8 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581464779] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581469259] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581473611] [image_format_converter_node.NitrosNode]: 	#9 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581478059] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581482859] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581486955] [image_format_converter_node.NitrosNode]: 	#10 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581491243] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581495499] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581499595] [image_format_converter_node.NitrosNode]: 	#11 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581504107] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb16
[component_container_mt-1] [DEBUG] [1709158194.581508299] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_rgb16
[component_container_mt-1] [DEBUG] [1709158194.581599820] [image_format_converter_node.NitrosNode]: 	#12 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581606764] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581613836] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581617836] [image_format_converter_node.NitrosNode]: 	#13 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581622060] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581625996] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581629804] [image_format_converter_node.NitrosNode]: 	#14 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581633677] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581681101] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581685421] [image_format_converter_node.NitrosNode]: 	#15 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581689485] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581693549] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581697549] [image_format_converter_node.NitrosNode]: 	#16 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581701581] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581705709] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581709709] [image_format_converter_node.NitrosNode]: 	#17 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581713741] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581717901] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581721869] [image_format_converter_node.NitrosNode]: 	#18 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581725965] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581730062] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581734062] [image_format_converter_node.NitrosNode]: 	#19 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581738094] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581742222] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581746158] [image_format_converter_node.NitrosNode]: 	#20 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581750638] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581754766] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581758734] [image_format_converter_node.NitrosNode]: 	#21 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581762830] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581766862] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581770862] [image_format_converter_node.NitrosNode]: 	#22 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581774798] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581779022] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581782926] [image_format_converter_node.NitrosNode]: 	#23 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581786894] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581790958] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581794894] [image_format_converter_node.NitrosNode]: 	#24 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581808814] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581814510] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581818766] [image_format_converter_node.NitrosNode]: 	#25 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581822831] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono16
[component_container_mt-1] [DEBUG] [1709158194.581827023] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_mono16
[component_container_mt-1] [DEBUG] [1709158194.581831023] [image_format_converter_node.NitrosNode]: 	#26 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581835023] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581840815] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581844815] [image_format_converter_node.NitrosNode]: 	#27 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581848719] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581852783] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581856655] [image_format_converter_node.NitrosNode]: 	#28 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581860591] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581864559] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581868399] [image_format_converter_node.NitrosNode]: 	#29 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581872367] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgba8
[component_container_mt-1] [DEBUG] [1709158194.581876303] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581894511] [image_format_converter_node.NitrosNode]: 	#30 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581898639] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_rgb8
[component_container_mt-1] [DEBUG] [1709158194.581902767] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581906767] [image_format_converter_node.NitrosNode]: 	#31 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581910799] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv24
[component_container_mt-1] [DEBUG] [1709158194.581914864] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581918864] [image_format_converter_node.NitrosNode]: 	#32 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581923696] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_nv12
[component_container_mt-1] [DEBUG] [1709158194.581928112] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581932080] [image_format_converter_node.NitrosNode]: 	#33 format combination:
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/image_format_converter_node' in container '/argus_mono_container'
[component_container_mt-1] [DEBUG] [1709158194.581936144] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_mono8
[component_container_mt-1] [DEBUG] [1709158194.581940304] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581944272] [image_format_converter_node.NitrosNode]: 	#34 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581948336] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgra8
[component_container_mt-1] [DEBUG] [1709158194.581952496] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581956528] [image_format_converter_node.NitrosNode]: 	#35 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581960528] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581964656] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr8
[component_container_mt-1] [DEBUG] [1709158194.581968624] [image_format_converter_node.NitrosNode]: 	#36 format combination:
[component_container_mt-1] [DEBUG] [1709158194.581972656] [image_format_converter_node.NitrosNode]: 		[in]	imageConverter/data_receiver: nitros_image_bgr16
[component_container_mt-1] [DEBUG] [1709158194.581992176] [image_format_converter_node.NitrosNode]: 		[out]	sink/sink: nitros_image_bgr16
[component_container_mt-1] [INFO] [1709158194.581997744] [image_format_converter_node]: [NitrosNode] Creating negotiated publishers/subscribers
[component_container_mt-1] [INFO] [1709158194.582173490] [image_format_converter_node]: [NitrosPublisherSubscriberGroup] Pinning the component "sink/sink" (type="nvidia::isaac_ros::MessageRelay") to use its compatible format only: "nitros_image_rgb8"
[component_container_mt-1] [DEBUG] [1709158194.582209683] [image_format_converter_node]: [NitrosPublisherSubscriberGroup] Filtering supported formats based on the compatible format for the component "sink/sink" (type="nvidia::isaac_ros::MessageRelay"): # of supported formats 36 -> 7
[component_container_mt-1] [DEBUG] [1709158194.582424405] [rcl]: Initializing subscription for topic name 'image_raw'
[component_container_mt-1] [DEBUG] [1709158194.582450549] [rcl]: Expanded and remapped topic name '/image_raw'
[component_container_mt-1] [DEBUG] [1709158194.586500321] [rcl]: Subscription initialized
[component_container_mt-1] [DEBUG] [1709158194.586701795] [image_format_converter_node.NitrosFormatAgent.nitros_image_mono8]: Created a compatible subscriber (topic_name=/image_raw, format_name=nitros_image_mono8)
[component_container_mt-1] [DEBUG] [1709158194.586824740] [rcl]: Initializing subscription for topic name '/image_raw/nitros'
[component_container_mt-1] [DEBUG] [1709158194.586843076] [rcl]: Expanded and remapped topic name '/image_raw/nitros'
[component_container_mt-1] [DEBUG] [1709158194.588590615] [rcl]: Subscription initialized
[component_container_mt-1] [DEBUG] [1709158194.588721977] [rcl]: Initializing publisher for topic name '/image_raw/nitros/_supported_types'
[component_container_mt-1] [DEBUG] [1709158194.588740377] [rcl]: Expanded and remapped topic name '/image_raw/nitros/_supported_types'
[component_container_mt-1] [DEBUG] [1709158194.589579586] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.589721667] [image_format_converter_node.NitrosFormatAgent.nitros_image_rgba8]: Added a supported format "nitros_image_rgba8" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589735235] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_rgba8"
[component_container_mt-1] [DEBUG] [1709158194.589778212] [image_format_converter_node.NitrosFormatAgent.nitros_image_rgb8]: Added a supported format "nitros_image_rgb8" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589786148] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_rgb8"
[component_container_mt-1] [DEBUG] [1709158194.589809316] [image_format_converter_node.NitrosFormatAgent.nitros_image_nv24]: Added a supported format "nitros_image_nv24" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589816068] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_nv24"
[component_container_mt-1] [DEBUG] [1709158194.589836613] [image_format_converter_node.NitrosFormatAgent.nitros_image_nv12]: Added a supported format "nitros_image_nv12" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589843077] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_nv12"
[component_container_mt-1] [DEBUG] [1709158194.589866277] [image_format_converter_node.NitrosFormatAgent.nitros_image_mono8]: Added a compatible subscriber (topic_name=/image_raw) to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589872901] [image_format_converter_node]: [NitrosSubscriber] Added a compatible subscriber: topic_name="/image_raw", data_format="nitros_image_mono8"
[component_container_mt-1] [DEBUG] [1709158194.589893861] [image_format_converter_node.NitrosFormatAgent.nitros_image_bgra8]: Added a supported format "nitros_image_bgra8" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589899333] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_bgra8"
[component_container_mt-1] [DEBUG] [1709158194.589919269] [image_format_converter_node.NitrosFormatAgent.nitros_image_bgr8]: Added a supported format "nitros_image_bgr8" to a negotiated subscriber
[component_container_mt-1] [DEBUG] [1709158194.589925126] [image_format_converter_node]: [NitrosSubscriber] Added a supported data format: topic_name="/image_raw", data_format="nitros_image_bgr8"
[component_container_mt-1] [DEBUG] [1709158194.590090855] [rcl]: Initializing publisher for topic name 'image'
[component_container_mt-1] [DEBUG] [1709158194.590106119] [rcl]: Expanded and remapped topic name '/image'
[component_container_mt-1] [DEBUG] [1709158194.590653165] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.590732718] [image_format_converter_node.NitrosFormatAgent.nitros_image_rgb8]: Created a compatible publisher (topic_name=/image)
[component_container_mt-1] [DEBUG] [1709158194.590789807] [rcl]: Initializing publisher for topic name '/image/nitros'
[component_container_mt-1] [DEBUG] [1709158194.590802191] [rcl]: Expanded and remapped topic name '/image/nitros'
[component_container_mt-1] [DEBUG] [1709158194.591306676] [rcl]: Publisher initialized
[component_container_mt-1] [DEBUG] [1709158194.591356725] [rcl]: Initializing wait set with '0' subscriptions, '2' guard conditions, '0' timers, '0' clients, '0' services
[component_container_mt-1] [DEBUG] [1709158194.591500854] [rcl]: Initializing timer with period: 100000000ns
[component_container_mt-1] [DEBUG] [1709158194.591584919] [image_format_converter_node.NitrosFormatAgent.nitros_image_rgb8]: Added a compatible publisher (topic_name=/image) to a negotiated publisher
[component_container_mt-1] [DEBUG] [1709158194.591607416] [image_format_converter_node]: [NitrosPublisher] Added a compatible publisher: topic_name="/image", data_format="nitros_image_rgb8"
[component_container_mt-1] [DEBUG] [1709158194.591635000] [image_format_converter_node]: [NitrosPublisherSubscriberGroup] An upstream subscriber added.
[component_container_mt-1] [INFO] [1709158194.591693209] [image_format_converter_node]: [NitrosNode] Starting negotiation...
[component_container_mt-1] [DEBUG] [1709158194.591752985] [rcl]: Initializing subscription for topic name '/image/nitros/_supported_types'
[component_container_mt-1] [DEBUG] [1709158194.591764761] [rcl]: Expanded and remapped topic name '/image/nitros/_supported_types'
[component_container_mt-1] [DEBUG] [1709158194.592307039] [rcl]: Subscription initialized
[component_container_mt-1] [DEBUG] [1709158194.592411296] [rcl]: Initializing timer with period: 1000000000ns
[component_container_mt-1] [DEBUG] [1709158194.592496097] [rcl]: Sending service response
[component_container_mt-1] [DEBUG] [1709158194.592676995] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.592745924] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.592763396] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.592790948] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.592935526] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.592993670] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593044231] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593073479] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593120296] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593142216] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593273193] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593302634] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593308298] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593334154] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593366698] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593394283] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593421323] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593435595] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593457483] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593470604] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593489676] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593503852] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593592557] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593607149] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593617997] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593625485] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593644493] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593657102] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593687022] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593700718] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593720878] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593748335] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.593841872] [rcl]: Subscription taking message
[component_container_mt-1] [DEBUG] [1709158194.593863440] [rcl]: Subscription take succeeded: true
[component_container_mt-1] [DEBUG] [1709158194.691734379] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158194.791718428] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158194.891689517] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158194.991680991] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.091674480] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.191674306] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.291942870] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.391887174] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.491693974] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.591673095] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.592549296] [rcl]: Calling timer
[component_container_mt-1] [DEBUG] [1709158195.592605681] [rcl]: Timer canceled
[component_container_mt-1] [INFO] [1709158195.592634385] [image_format_converter_node]: [NitrosNode] Starting post negotiation setup
[component_container_mt-1] [INFO] [1709158195.592723218] [image_format_converter_node]: [NitrosNode] Getting data format negotiation results
[component_container_mt-1] [INFO] [1709158195.592770451] [image_format_converter_node]: [NitrosPublisher] Negotiation ended with no results
[component_container_mt-1] [INFO] [1709158195.592798387] [image_format_converter_node]: [NitrosPublisher] Use only the compatible publisher: topic_name="/image", data_format="nitros_image_rgb8"
[component_container_mt-1] [INFO] [1709158195.592829875] [image_format_converter_node]: [NitrosSubscriber] Negotiation ended with no results
[component_container_mt-1] [INFO] [1709158195.592852275] [image_format_converter_node]: [NitrosSubscriber] Use the compatible subscriber: topic_name="/image_raw", data_format="nitros_image_mono8"
[component_container_mt-1] [INFO] [1709158195.593455354] [image_format_converter_node]: [NitrosNode] Exporting the final graph based on the negotiation results
[component_container_mt-1] [INFO] [1709158195.623550813] [image_format_converter_node]: [NitrosNode] Wrote the final top level YAML graph to "/tmp/isaac_ros_nitros/graphs/XYWCBZJCLI/XYWCBZJCLI.yaml"
[component_container_mt-1] [INFO] [1709158195.623731519] [image_format_converter_node]: [NitrosNode] Calling user's pre-load-graph callback
[component_container_mt-1] [INFO] [1709158195.623767295] [image_format_converter_node]: [NitrosNode] Loading application
[component_container_mt-1] [INFO] [1709158195.623798464] [image_format_converter_node]: [NitrosContext] Loading application: '/tmp/isaac_ros_nitros/graphs/XYWCBZJCLI/XYWCBZJCLI.yaml'
[component_container_mt-1] [INFO] [1709158195.626923713] [image_format_converter_node]: [NitrosNode] Linking Nitros pub/sub to the loaded application
[component_container_mt-1] [DEBUG] [1709158195.627133315] [image_format_converter_node]: [NitrosNode] Setting a subscriber's pointer: 0xffff4834c5f0
[component_container_mt-1] [DEBUG] [1709158195.627324709] [image_format_converter_node]: [NitrosNode] Set a publisher's callback pointer: 0xffff84b76878
[component_container_mt-1] [INFO] [1709158195.627365990] [image_format_converter_node]: [NitrosNode] Calling user's post-load-graph callback
[component_container_mt-1] [INFO] [1709158195.627391558] [image_format_converter_node]: [ImageFormatConverterNode] postLoadGraphCallback().
[component_container_mt-1] [INFO] [1709158195.627414502] [image_format_converter_node]: [NitrosContext] Initializing application...
[component_container_mt-1] 2024-02-28 14:09:56.116 ERROR /workspaces/isaac_ros_stuff/src/isaac_ros_image_pipeline/isaac_ros_image_proc/gxf/tensorops/extensions/tensorops/components/TensorStream.cpp@104: tensor stream creation failed.
[component_container_mt-1] 2024-02-28 14:09:56.116 ERROR gxf/std/entity_warden.cpp@406: Failed to initialize component 00030 (stream)
[component_container_mt-1] 2024-02-28 14:09:56.116 ERROR gxf/core/runtime.cpp@685: Could not initialize entity 'XYWCBZJCLI_resource' (E28): GXF_FAILURE
[component_container_mt-1] 2024-02-28 14:09:56.116 ERROR gxf/std/program.cpp@236: Failed to activate entity 00028 named XYWCBZJCLI_resource: GXF_FAILURE
[component_container_mt-1] 2024-02-28 14:09:56.116 ERROR gxf/std/program.cpp@238: Deactivating...
[component_container_mt-1] 2024-02-28 14:09:56.131 ERROR gxf/core/runtime.cpp@1384: Graph activation failed with error: GXF_FAILURE
[component_container_mt-1] [ERROR] [1709158196.131253830] [image_format_converter_node]: [NitrosContext] GxfGraphActivate Error: GXF_FAILURE
[component_container_mt-1] [ERROR] [1709158196.131412072] [image_format_converter_node]: [NitrosNode] runGraphAsync Error: GXF_FAILURE
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-1]   what():  [NitrosNode] runGraphAsync Error: GXF_FAILURE
[ERROR] [component_container_mt-1]: process has died [pid 288864, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args --log-level debug --ros-args -r __node:=argus_mono_container -r __ns:=/ -r image_raw:=/camera/rs_top/infra1/image_rect_raw -r camera_info:=/camera/rs_top/infra1/camera_info'].

**Comment by jaiveersinghNV** [comment]
Are you using X11 forwarding by any chance?

Take a look at our [troubleshooting steps](https://nvidia-isaac-ros.github.io/troubleshooting/dev_env.html#gxf-failure-due-to-tensor-stream-creation-failed) for the tensor stream creation error you're seeing.

**Comment by sandeepdutta** [comment]
Hello Jaiveer,

Yes indeed X11 forwarding was the issue. Thank you for your respnse. I am closing this issue.
Best Regards
Sandeep
